### ISSUE TITLE
Create buttons

### ISSUE THREAD

**Issue by SSais** [SchoolOfCode/bc17-w7d3-workshop-nextjs-boilerplate-uncle-free-to-play#2]
```[tasklist]
### Tasks
- [x] Create a new component called review
- [x] Create react function
- [x] Link css and jsx
- [x] Create html for three buttons
- [x] Link to main page and test if the button shows
```
